language: bash

services:
  - docker

install:
  - travis_retry make install-php COMPOSER_FLAGS="-q --no-scripts"

script:
  - make ci-with-coverage COVERAGE_FLAGS="--coverage-clover coverage.clover"
  - make install-php COMPOSER_FLAGS="--no-dev -q --no-scripts" # Remove dev dependencies to make sure PHPStan creates errors if prod code depends on dev classes
  - docker run -v $PWD:/app --rm registry.gitlab.com/fun-tech/fundraising-frontend-docker/php-8.1:stan analyse --configuration=phpstan.prod.neon --level 7 --no-progress src/

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

cache:
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/phpstan"

notifications:
  email:
    on_success: change
    on_failure: always
