language: bash

services:
  - docker

install:
  - travis_retry make install-php

before_script:
  - if [ ! -f "$HOME/phpstan/phpstan_$PHPSTAN_VERSION.phar" ]; then mkdir -p $HOME/phpstan; curl -L https://github.com/phpstan/phpstan/releases/download/$PHPSTAN_VERSION/phpstan.phar > $HOME/phpstan/phpstan_$PHPSTAN_VERSION.phar; chmod +x $HOME/phpstan/phpstan_$PHPSTAN_VERSION.phar; fi

script:
  - make ci-with-coverage
  - make install-php COMPOSER_FLAGS="--no-dev -q --no-scripts" # Remove dev dependencies to make sure PHPStan creates errors if prod code depends on dev classes
  - docker-compose run --rm app -v $HOME/phpstan/phpstan_$PHPSTAN_VERSION.phar:/usr/share/nginx/www/banner.wikipedia.de/current/phpstan phpstan analyse --level=7 --no-progress src/ tests/

after_success:
  - bash build/travis/uploadCoverage.sh

cache:
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/phpstan"

notifications:
  email:
    on_success: change
    on_failure: always

env:
  global:
    - PHPSTAN_VERSION=0.10.5