language: bash

services:
  - docker

install:
  - travis_retry make install-php

script:
  - make ci-with-coverage
  - make install-php COMPOSER_FLAGS="--no-dev -q --no-scripts" # Remove dev dependencies to make sure PHPStan creates errors if prod code depends on dev classes
  - docker run -v $PWD:/app --rm  wikimediade/fundraising-frontend:stan analyse --configuration=phpstan.prod.neon --level 7 --no-progress src/

after_success:
  - bash build/travis/uploadCoverage.sh

cache:
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/phpstan"

notifications:
  email:
    on_success: change
    on_failure: always
