language: bash

services:
  - docker

install:
  - travis_retry make install-php COMPOSER_FLAGS="-q --no-scripts"

script:
  - make ci-with-coverage COVERAGE_FLAGS="--coverage-clover coverage.clover"
    # Remove dev dependencies to make sure PHPStan creates errors if prod code depends on dev classes
    # TODO: Replace with deptrac, see https://phabricator.wikimedia.org/T277873
  - make install-php COMPOSER_FLAGS="--no-dev -q --no-scripts"
  - wget https://github.com/phpstan/phpstan/releases/download/1.10.57/phpstan.phar -O $PWD/phpstan.phar
  - docker run -v $PWD:/app -w /app --rm php:8.1-fpm-buster php phpstan.phar analyse --configuration=phpstan.prod.neon --level 7 --no-progress --no-interaction --memory-limit=1024M src/

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

cache:
  directories:
  - "$HOME/.composer/cache"

notifications:
  email:
    on_success: change
    on_failure: always
