version: '3.4'

services:
  app:
    build:
      context: ./build/app
      target: app
    expose:
    - "9000"
    volumes:
    - .:/usr/share/nginx/www/banner.wikipedia.de/current
    - var-data:/usr/share/nginx/www/banner.wikipedia.de/current/var
    working_dir: /usr/share/nginx/www/banner.wikipedia.de/current

  proxy:
    image: nginx:stable
    links:
    - app
    ports:
    - "8088:8080"
    volumes:
    - ./build/proxy/nginx.conf.template:/etc/nginx/conf.d/nginx.conf.template:ro
    - ./public:/usr/share/nginx/www/banner.wikipedia.de/current/public:ro
    environment:
    - NGINX_HOST=banner.wikipedia.de
    - NGINX_PORT=8080
    - PHP_FPM_HOST=app
    command: /bin/bash -c "envsubst '$$NGINX_HOST $$NGINX_PORT $$PHP_FPM_HOST' < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"


volumes:
  var-data:

networks:
  frontend-proxy: